version: 1.0.{build}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn distwin

test: off

artifacts:
  - path: 'build\*.exe'
