version: 1.0.{build}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "false" move '**\GNS3-*-all-in-one*.exe' .
  - cmd: IF "%APPVEYOR_REPO_TAG%" == "false" Get-ChildItem -Filter '*.exe' | Rename-Item -NewName {$_.Name -replace ".exe","-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_NUMBER%.exe"}

build_script:
  - yarn distwin

test: off

artifacts:
  - path: '*.exe'

deploy:
  - provider: FTP
    protocol: sftp
    host: frs.sourceforge.net
    username: gns3build
    password:
      secure: YRiLLoY27UOZ8QJHqqdESBQFfPfENKV0cLI/QFSsbWc=
    folder: "../../../../frs/project/gns-3/Continuous"
    on:
      appveyor_repo_tag: false # deploy on branch only
