version: 1.0.{build}

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

platform:
  - x64

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn distwin
  - ps: If ($env:APPVEYOR_REPO_TAG -eq $false) { New-Item -ItemType Directory -Path ".\$((Get-Date).ToString('yyyy-MM-dd'))" }
  - ps: If ($env:APPVEYOR_REPO_TAG -eq $false) { move build\*.exe $((Get-Date).ToString('yyyy-MM-dd')) }
  - ps: If ($env:APPVEYOR_REPO_TAG -eq $false) { cd $((Get-Date).ToString('yyyy-MM-dd')); Get-ChildItem -Filter '*.exe' | Rename-Item -NewName {$_.Name -replace ".exe","-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER.exe"} }
  - ps: If ($env:APPVEYOR_REPO_TAG -eq $false) { cd ..; Push-AppveyorArtifact "$((Get-Date).ToString('yyyy-MM-dd'))\*.exe" }

test: off

#artifacts:
#  - path: '**\GNS3 Web UI Prototype-*.exe'

deploy:
  - provider: FTP
    protocol: sftp
    host: frs.sourceforge.net
    username: gns3build
    password:
      secure: YRiLLoY27UOZ8QJHqqdESBQFfPfENKV0cLI/QFSsbWc=
    folder: "../../../../frs/project/gns-3/Nightly Builds"
    artifact: /.*\.exe/
    on:
      appveyor_repo_tag: false # deploy on branch only
