# iOS CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    macos:
      xcode: "9.1.0"

    steps:
      - checkout

      - run:
          name: Set timezone and check current datetime
          command: |
            sudo systemsetup -settimezone Europe/Warsaw
            echo "Today is $(date +"%Y-%m-%d %T")"

      - run:
          name: Install project
          # there is an issue with yarn and cache during executed on CI; for now we just run it twice, second should
          # be successful. Check it later if updates fixed the issue
          command: |
            yarn || true
            yarn || true

      - run:
          name: Dist project
          command: |
            yarn distmac

      - run:
          name: Gather artifacts
          command: |
            mkdir artifacts
            cp build/*.dmg artifacts/

      - store_artifacts:
          path: artifacts
          destination: artifacts
