# iOS CircleCI 2.0 configuration file
version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "9.1.0"

    steps:
      - checkout

      - run:
          name: Set timezone and check current datetime
          command: |
            sudo systemsetup -settimezone Europe/Warsaw
            echo "Today is $(date +"%Y-%m-%d %T")"

#      - run:
#          name: Update BREW
#          command: |
#            brew update
#
#      - run:
#          name: Install Yarn
#          command: |
#            brew upgrade yarn
#

      - run:
          name: Fix Yarn
          command: |
            brew uninstall yarn
            curl -o- -L https://yarnpkg.com/install.sh | bash
            echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' > ~/.bash_profile
            source ~/.bash_profile

      - run:
          name: Install project
          command: |
            yarn install --network-concurrency 1

      - run:
          name: Dist project
          command: |
            yarn distmac

      - run:
          name: Gather artifacts
          command: |
            mkdir artifacts
            cp build/*.exe artifacts/

      - store_artifacts:
          path: artifacts
          destination: artifacts
